baseURL = "https://CyberPianist.github.io/"
languageCode = "zh-cn"
title = "CyberPianist"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  ShowReadingTime = true
  ShowToc = true
  defaultTheme = "auto"
